config/routes.rb
Rails.application.routes.draw do
  resources :projekts
  devise_for :users
  devise_for :views
  resources :praktikanters
  #get 'home/index'
  get 'home/about'
  root 'home#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/praktikanter.rb
class Praktikanter < ApplicationRecord
    belongs_to :user
end

app/models/projekt.rb
class Projekt < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :praktikanter
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def about
  end
  
end

app/controllers/praktikanters_controller.rb
class PraktikantersController < ApplicationController
  before_action :set_praktikanter, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index,]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /praktikanters or /praktikanters.json
  def index
    @praktikanters = Praktikanter.all
  end

  # GET /praktikanters/1 or /praktikanters/1.json
  def show
  end

  # GET /praktikanters/new
  def new
    #@praktikanter = Praktikanter.new
    @praktikanter = current_user.praktikanter.new
  end

  # GET /praktikanters/1/edit
  def edit
  end

  # POST /praktikanters or /praktikanters.json
  def create
    #@praktikanter = Praktikanter.new(praktikanter_params)
    @praktikanter = current_user.praktikanter.build(praktikanter_params)
    respond_to do |format|
      if @praktikanter.save
        format.html { redirect_to praktikanter_url(@praktikanter), notice: "Praktikant har skapats." }
        format.json { render :show, status: :created, location: @praktikanter }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @praktikanter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /praktikanters/1 or /praktikanters/1.json
  def update
    respond_to do |format|
      if @praktikanter.update(praktikanter_params)
        format.html { redirect_to praktikanter_url(@praktikanter), notice: "Praktikant har uppdaterats." }
        format.json { render :show, status: :ok, location: @praktikanter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @praktikanter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /praktikanters/1 or /praktikanters/1.json
  def destroy
    @praktikanter.destroy

    respond_to do |format|
      format.html { redirect_to praktikanters_url, notice: "Praktikant har tagits bort." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @praktikanter = current_user.praktikanter.find_by(id: params[:id])
    redirect_to praktikanter_path, notice: "Saknar behörighet" if @praktikanter.nil?
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_praktikanter
      @praktikanter = Praktikanter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def praktikanter_params
      params.require(:praktikanter).permit(:first_förnamn, :efternamn, :email, :telefon, :linkedin, :user_id)
    end
end

app/controllers/projekts_controller.rb
class ProjektsController < ApplicationController
  before_action :set_projekt, only: %i[ show edit update destroy ]

  # GET /projekts or /projekts.json
  def index
    @projekts = Projekt.all
  end

  # GET /projekts/1 or /projekts/1.json
  def show
  end

  # GET /projekts/new
  def new
    @projekt = Projekt.new
  end

  # GET /projekts/1/edit
  def edit
  end

  # POST /projekts or /projekts.json
  def create
    @projekt = Projekt.new(projekt_params)

    respond_to do |format|
      if @projekt.save
        format.html { redirect_to projekt_url(@projekt), notice: "Projekt was successfully created." }
        format.json { render :show, status: :created, location: @projekt }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @projekt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projekts/1 or /projekts/1.json
  def update
    respond_to do |format|
      if @projekt.update(projekt_params)
        format.html { redirect_to projekt_url(@projekt), notice: "Projekt was successfully updated." }
        format.json { render :show, status: :ok, location: @projekt }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @projekt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projekts/1 or /projekts/1.json
  def destroy
    @projekt.destroy

    respond_to do |format|
      format.html { redirect_to projekts_url, notice: "Projekt was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projekt
      @projekt = Projekt.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def projekt_params
      params.require(:projekt).permit(:namn, :beskrivning, :ägare, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/praktikanters_helper.rb
module PraktikantersHelper
end

app/helpers/projekts_helper.rb
module ProjektsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">StandIn</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    	<%= link_to 'Hem', root_path, class:"nav-link"%>
      </li>

    <% if user_signed_in? %>
       <li class="nav-item">
      	<%= link_to 'Logga ut', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
      <li class="nav-item">
      	<%= link_to 'Redigera profil', edit_user_registration_path, class: 'nav-link' %>
      </li>

    <% else %>
      <li class="nav-item">
      	<%= link_to 'Logga in', new_user_session_path, class: 'nav-link' %>
      </li>
     
      <li class="nav-item">
      	<%= link_to 'Registrera', new_user_registration_path, class: 'nav-link' %>
      </li>
    <% end %>
      
      <% if user_signed_in? %>
       <li class="nav-item">
      	<%= link_to 'Projekt', projekts_path, class: 'nav-link'%>
         </li>
         <% end %>
      
      <li class="nav-item">
      	<%= link_to 'Praktikanter', praktikanters_path, class: 'nav-link'%>
         </li>

         <li class="nav-item">
      	<%= link_to 'Om oss', home_about_path, class: 'nav-link' %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Sök" aria-label="Search">
      <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Sök</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1> Om oss...</h1>
<p> Detta är en sida som skapats under praktiken för att få lärdom kring programmering. 
Målet med sidan är att den ska utvecklas under hela praktikperioden med nya funktioner och metoder som jag lär mig under dessa 6 månader.</p>

app/views/home/index.html.erb
<h1>Hejsan Standout!</h1>
<p>Detta är ett test för att se hur webbsidan fungerar.</p>

<img src="https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" class="rounded float-start" alt="...">

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice%>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>Kontakt</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>

    <%= render 'home/header'%>
    <div class="container">
   <br>
    <% if notice %>
      <%= render 'layouts/alerts'%>
    <% end %>

      <br/>
     <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/praktikanters/_form.html.erb
<%= form_with(model: praktikanter) do |form| %>
  <% if praktikanter.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(praktikanter.errors.count, "error") %> prohibited this praktikanter from being saved:</h2>

      <ul>
        <% praktikanter.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :förnamn, style: "display: block" %>
    <%= form.text_field :first_förnamn, class: "form-control" %>
  </div>

  <div>
    <%= form.label :efternamn, style: "display: block" %>
    <%= form.text_field :efternamn, class: "form-control" %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div>
    <%= form.label :telefon, style: "display: block" %>
    <%= form.text_field :telefon, class: "form-control" %>
  </div>

  <div>
    <%= form.label :linkedin, style: "display: block" %>
    <%= form.text_field :linkedin, class: "form-control" %>
  </div>

  <div>
    
    <%= form.number_field :ID, id: :praktikant_id, class: "form-control", value: current_user.id, type: :hidden %>
  </div>

<br>
  <div>
    <%= form.submit class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/praktikanters/_praktikanter.html.erb
<div id="<%= dom_id praktikanter %>">
  <tbody>
    <tr>
    <td><%= praktikanter.first_förnamn %></td>
    <td><%= praktikanter.efternamn %></td>
    <td><%= praktikanter.email %></td>
    <td><%= praktikanter.telefon %> </td>
    <td><%= praktikanter.linkedin %></td>
    <td><%= link_to "Visa", praktikanter %></td>
   </tr>

app/views/praktikanters/edit.html.erb
<h1>Redigera praktikant</h1>

<%= render "form", praktikanter: @praktikanter %>


<div>
<%= button_to "Ta bort", @praktikanter, method: :delete, class: 'btn btn-danger', data: { confirm: "Är du säker?" } %>
 <br>
  <%= link_to "Tillbaka", praktikanters_path, class: 'btn btn-secondary' %>
  
</div>

app/views/praktikanters/index.html.erb
<h1>Praktikanter</h1>
<div id="praktikanters">
  <table class="table table-secondary table-bordered border-dark table-hover">
  <br>
    <thead>
      <tr>
        <th scope="col">Förnamn</th>
        <th scope="col">Efternamn</th>
        <th scope="col">Email</th>
        <th scope="col">Telefon</th>
        <th scope="col">LinkedIn</th>
      </tr>
    </thead>
    <% @praktikanters.each do |praktikanter| %>
      <%= render praktikanter %>
    <% end %>
  </table>
</div>
<%= link_to "Ny praktikant", new_praktikanter_path, class:"btn btn-secondary" %>

app/views/praktikanters/new.html.erb
<h1>Ny praktikant</h1>

<%= render "form", praktikanter: @praktikanter %>

<br>

<div>
  <%= link_to "Tillbaka", praktikanters_path, class: 'btn btn-secondary' %>
</div>

app/views/praktikanters/show.html.erb
<div class="card text-center">
  <div class="card-header">
PRAKTIKANT
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= @praktikanter.first_förnamn %>
    <%= @praktikanter.efternamn %></h5>
    <p class="card-text"><%= @praktikanter.email %> </p>
      <p class="card-text"><%= @praktikanter.telefon %> </p>
    <%= link_to 'LinkedIn', @praktikanter.linkedin, class:, class: "btn btn-primary" %>
  </div>
  <div class="card-footer text-muted">
     <%= link_to "Redigera", edit_praktikanter_path(@praktikanter), class:"btn btn-secondary" %>
  <%= link_to "Tillbaka", praktikanters_path, class:"btn btn-secondary" %>
  </div>
</div>
 <img src="https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" class="rounded float-start" alt="...">

app/views/projekts/_form.html.erb
<%= form_with(model: projekt) do |form| %>
  <% if projekt.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(projekt.errors.count, "error") %> prohibited this projekt from being saved:</h2>

      <ul>
        <% projekt.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :namn, style: "display: block" %>
    <%= form.text_field :namn, class: "form-control" %>
  </div>

  <div>
    <%= form.label :beskrivning, style: "display: block" %>
    <%= form.text_area :beskrivning, class: "form-control" %>
  </div>

  <div>
    <%= form.label :projektägare, style: "display: block" %>
    <%= form.text_field :ägare, class: "form-control" %>
  </div>

<br/>

  <div>
    <select class="form-select" aria-label="Status">
  <option selected>Välj status</option>
  <option value="1">Startad</option>
  <option value="2">Påbörjad</option>
  <option value="3">Avslutad</option>
</select>
  </div>
  
  <br/>

  <div>
    <%= form.submit :"Skapa projekt", class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/projekts/_projekt.html.erb
<div id="<%= dom_id projekt %>">
<tbody>
    <tr>
    <td><%= projekt.namn %></td>
    <td><%= projekt.beskrivning %></td>
    <td><%= projekt.ägare %></td>
    <td><%= projekt.status %></td>
    <td><%= link_to "Visa", projekt %></td>
   </tr>

</div>

app/views/projekts/edit.html.erb
<h1>Editing projekt</h1>

<%= render "form", projekt: @projekt %>

<br>

<div>
  <%= link_to "Visa", @projekt %> |
  <%= link_to "Tillbaka", projekts_path %>
</div>

app/views/projekts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projekt</h1>

<div id="projekts">
<table class="table table-secondary table-bordered border-dark table-hover">
<br>
    <thead>
      <tr>
        <th scope="col">Namn</th>
        <th scope="col">Beskrivning</th>
        <th scope="col">Ägare</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
  <% @projekts.each do |projekt| %>
    <%= render projekt %>

  <% end %>
</div>

<%= link_to "New projekt", new_projekt_path, class:"btn btn-secondary" %>

app/views/projekts/new.html.erb
<h1>New projekt</h1>

<%= render "form", projekt: @projekt %>

<br>

<div>
  <%= link_to "Back to projekts", projekts_path %>
</div>

app/views/projekts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @projekt %>

<div>
  <%= link_to "Edit this projekt", edit_projekt_path(@projekt) %> |
  <%= link_to "Back to projekts", projekts_path %>

  <%= button_to "Destroy this projekt", @projekt, method: :delete %>
</div>